//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remote.SrzServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="People", Namespace="http://schemas.datacontract.org/2004/07/SrzService.DataModel")]
    [System.SerializableAttribute()]
    public partial class People : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatronymicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeopleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENP {
            get {
                return this.ENPField;
            }
            set {
                if ((object.ReferenceEquals(this.ENPField, value) != true)) {
                    this.ENPField = value;
                    this.RaisePropertyChanged("ENP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic {
            get {
                return this.PatronymicField;
            }
            set {
                if ((object.ReferenceEquals(this.PatronymicField, value) != true)) {
                    this.PatronymicField = value;
                    this.RaisePropertyChanged("Patronymic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeopleId {
            get {
                return this.PeopleIdField;
            }
            set {
                if ((this.PeopleIdField.Equals(value) != true)) {
                    this.PeopleIdField = value;
                    this.RaisePropertyChanged("PeopleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Policy", Namespace="http://schemas.datacontract.org/2004/07/SrzService.DataModel")]
    [System.SerializableAttribute()]
    public partial class Policy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateBeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateStopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PeopleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PolicyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicySerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PolicyTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateBegin {
            get {
                return this.DateBeginField;
            }
            set {
                if ((this.DateBeginField.Equals(value) != true)) {
                    this.DateBeginField = value;
                    this.RaisePropertyChanged("DateBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateEnd {
            get {
                return this.DateEndField;
            }
            set {
                if ((this.DateEndField.Equals(value) != true)) {
                    this.DateEndField = value;
                    this.RaisePropertyChanged("DateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateStop {
            get {
                return this.DateStopField;
            }
            set {
                if ((this.DateStopField.Equals(value) != true)) {
                    this.DateStopField = value;
                    this.RaisePropertyChanged("DateStop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PeopleId {
            get {
                return this.PeopleIdField;
            }
            set {
                if ((this.PeopleIdField.Equals(value) != true)) {
                    this.PeopleIdField = value;
                    this.RaisePropertyChanged("PeopleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PolicyId {
            get {
                return this.PolicyIdField;
            }
            set {
                if ((this.PolicyIdField.Equals(value) != true)) {
                    this.PolicyIdField = value;
                    this.RaisePropertyChanged("PolicyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber {
            get {
                return this.PolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNumberField, value) != true)) {
                    this.PolicyNumberField = value;
                    this.RaisePropertyChanged("PolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicySerial {
            get {
                return this.PolicySerialField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicySerialField, value) != true)) {
                    this.PolicySerialField = value;
                    this.RaisePropertyChanged("PolicySerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PolicyType {
            get {
                return this.PolicyTypeField;
            }
            set {
                if ((this.PolicyTypeField.Equals(value) != true)) {
                    this.PolicyTypeField = value;
                    this.RaisePropertyChanged("PolicyType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrzServiceReference.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CheckConfig", ReplyAction="http://tempuri.org/IDataService/CheckConfigResponse")]
        string CheckConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Auth", ReplyAction="http://tempuri.org/IDataService/AuthResponse")]
        System.Nullable<int> Auth(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CheckPolicy", ReplyAction="http://tempuri.org/IDataService/CheckPolicyResponse")]
        bool CheckPolicy(int policyType, string policyNumber, System.DateTime eventBegin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPeopleListByPolicy", ReplyAction="http://tempuri.org/IDataService/GetPeopleListByPolicyResponse")]
        Remote.SrzServiceReference.People[] GetPeopleListByPolicy(int policyType, string policyNumber, string policySeries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPeopleListByPersonal", ReplyAction="http://tempuri.org/IDataService/GetPeopleListByPersonalResponse")]
        Remote.SrzServiceReference.People[] GetPeopleListByPersonal(string surname, string name, string patronymic, System.Nullable<System.DateTime> birthday, System.Nullable<int> sex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPeopleByPolicy", ReplyAction="http://tempuri.org/IDataService/GetPeopleByPolicyResponse")]
        Remote.SrzServiceReference.People GetPeopleByPolicy(int policyType, string policy, string series);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPeopleByPolicyObj", ReplyAction="http://tempuri.org/IDataService/GetPeopleByPolicyObjResponse")]
        Remote.SrzServiceReference.People GetPeopleByPolicyObj(Remote.SrzServiceReference.Policy policy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPeopleById", ReplyAction="http://tempuri.org/IDataService/GetPeopleByIdResponse")]
        Remote.SrzServiceReference.People GetPeopleById(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPolicyByPeopleId", ReplyAction="http://tempuri.org/IDataService/GetPolicyByPeopleIdResponse")]
        Remote.SrzServiceReference.Policy[] GetPolicyByPeopleId(System.Nullable<int> id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : Remote.SrzServiceReference.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<Remote.SrzServiceReference.IDataService>, Remote.SrzServiceReference.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckConfig() {
            return base.Channel.CheckConfig();
        }
        
        public System.Nullable<int> Auth(string userName, string password) {
            return base.Channel.Auth(userName, password);
        }
        
        public bool CheckPolicy(int policyType, string policyNumber, System.DateTime eventBegin) {
            return base.Channel.CheckPolicy(policyType, policyNumber, eventBegin);
        }
        
        public Remote.SrzServiceReference.People[] GetPeopleListByPolicy(int policyType, string policyNumber, string policySeries) {
            return base.Channel.GetPeopleListByPolicy(policyType, policyNumber, policySeries);
        }
        
        public Remote.SrzServiceReference.People[] GetPeopleListByPersonal(string surname, string name, string patronymic, System.Nullable<System.DateTime> birthday, System.Nullable<int> sex) {
            return base.Channel.GetPeopleListByPersonal(surname, name, patronymic, birthday, sex);
        }
        
        public Remote.SrzServiceReference.People GetPeopleByPolicy(int policyType, string policy, string series) {
            return base.Channel.GetPeopleByPolicy(policyType, policy, series);
        }
        
        public Remote.SrzServiceReference.People GetPeopleByPolicyObj(Remote.SrzServiceReference.Policy policy) {
            return base.Channel.GetPeopleByPolicyObj(policy);
        }
        
        public Remote.SrzServiceReference.People GetPeopleById(System.Nullable<int> id) {
            return base.Channel.GetPeopleById(id);
        }
        
        public Remote.SrzServiceReference.Policy[] GetPolicyByPeopleId(System.Nullable<int> id) {
            return base.Channel.GetPolicyByPeopleId(id);
        }
    }
}
