// <auto-generated />
namespace Medical.DatabaseCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FixF014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixF014));
        
        string IMigrationMetadata.Id
        {
            get { return "201501130851538_FixF014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
