// <auto-generated />
namespace Medical.DatabaseCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddF004Fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddF004Fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201503270853119_AddF004Fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
